(function(i){typeof define=="function"&&define.amd?define(i):i()})(function(){"use strict";var f=i=>{throw TypeError(i)};var a=(i,s,e)=>s.has(i)||f("Cannot "+e);var r=(i,s,e)=>(a(i,s,"read from private field"),e?e.call(i):s.get(i)),h=(i,s,e)=>s.has(i)?f("Cannot add the same private member more than once"):s instanceof WeakSet?s.add(i):s.set(i,e),l=(i,s,e,u)=>(a(i,s,"write to private field"),u?u.call(i,e):s.set(i,e),e),d=(i,s,e)=>(a(i,s,"access private method"),e);var s,e,u,o,m,p,v,b;class i extends HTMLElement{constructor(){super();h(this,o);h(this,s);h(this,e);h(this,u)}connectedCallback(){this.innerHTML=`
			<div class="screen">
				<div class="output">
				</div>
				<form class="input" action="#">
					<input type="text" value="" />
					<input type="submit" value="" />
				</form>
			</div>
		`,l(this,s,this.querySelector(".output")),l(this,e,this.querySelector('form.input input[type="text"]')),l(this,u,{resolve:()=>{},reject:()=>{}}),d(this,o,m).call(this),requestAnimationFrame(()=>{this.dispatchEvent(new CustomEvent("ready"))})}out(t,n=""){const c=document.createElement("pre");["error","warning","warn","success","info","debug"].includes(n)&&c.classList.add(n),c.textContent=t,r(this,s).appendChild(c),this.scrollTo(0,this.scrollHeight)}outError(t){this.out(t,"error")}outWarning(t){this.out(t,"warning")}outWarn(t){this.outWarning(t)}outSuccess(t){this.out(t,"success")}outInfo(t){this.out(t,"info")}outDebug(t){this.out(t,"debug")}in(t){return t&&this.out(t),new Promise((n,c)=>{l(this,u,{resolve:n,reject:c})})}open(t){const n=t==null||t==null?`
ObsiCLI was opened correctly.`:t;this.out(n),r(this,e).removeAttribute("disabled"),r(this,e).focus(),d(this,o,p).call(this,"opened")}close(t){const n=t==null||t==null?`
ObsiCLI was closed correctly.`:t;this.out(n),r(this,e).setAttribute("disabled","disabled"),r(this,e).value="",d(this,o,p).call(this,"closed")}}s=new WeakMap,e=new WeakMap,u=new WeakMap,o=new WeakSet,m=function(){const t=this.querySelector(".input");t instanceof HTMLFormElement&&t.addEventListener("submit",d(this,o,v).bind(this)),this.addEventListener("click",d(this,o,b).bind(this))},p=function(t){const n=new CustomEvent(t);this.dispatchEvent(n)},v=function(t){t.preventDefault(),this.out(r(this,e).value),r(this,u).resolve(r(this,e).value),t.currentTarget.reset(),l(this,u,{resolve:()=>{},reject:()=>{}})},b=function(){requestAnimationFrame(()=>{const t=window.getSelection();let n=!1;t.isCollapsed||t.anchorNode.parentNode.closest("obsi-cli")===this&&(n=!0),n||r(this,e).focus()})},customElements.define("obsi-cli",i)});
