(function(i){typeof define=="function"&&define.amd?define(i):i()})((function(){"use strict";var f=i=>{throw TypeError(i)};var p=(i,s,e)=>s.has(i)||f("Cannot "+e);var o=(i,s,e)=>(p(i,s,"read from private field"),e?e.call(i):s.get(i)),d=(i,s,e)=>s.has(i)?f("Cannot add the same private member more than once"):s instanceof WeakSet?s.add(i):s.set(i,e),h=(i,s,e,r)=>(p(i,s,"write to private field"),r?r.call(i,e):s.set(i,e),e),l=(i,s,e)=>(p(i,s,"access private method"),e);var s,e,r,u,v,a,b,m;class i extends HTMLElement{constructor(){super();d(this,u);d(this,s);d(this,e);d(this,r)}connectedCallback(){this.innerHTML=`
			<div class="screen">
				<div class="output">
				</div>
				<form class="input" action="#">
					<input type="text" value="" />
					<input type="submit" value="" />
				</form>
			</div>
		`,h(this,s,this.querySelector(".output")),h(this,e,this.querySelector('form.input input[type="text"]')),h(this,r,{resolve:()=>{},reject:()=>{}}),l(this,u,v).call(this),requestAnimationFrame(()=>{this.dispatchEvent(new CustomEvent("ready"))})}out(t,n=""){const c=document.createElement("pre");["error","warning","warn","success","info","debug"].includes(n)&&c.classList.add(n),c.textContent=typeof t=="object"?JSON.stringify(t,null,2):t,o(this,s).appendChild(c),this.scrollTo(0,this.scrollHeight)}outError(t){this.out(t,"error")}outWarning(t){this.out(t,"warning")}outWarn(t){this.outWarning(t)}outSuccess(t){this.out(t,"success")}outInfo(t){this.out(t,"info")}outDebug(t){this.out(t,"debug")}in(t){return t&&this.out(t),new Promise((n,c)=>{h(this,r,{resolve:n,reject:c})})}open(t){const n=t==null||t==null?`
ObsiCLI was opened correctly.`:t;this.out(n),o(this,e).removeAttribute("disabled"),o(this,e).focus(),l(this,u,a).call(this,"opened")}close(t){const n=t==null||t==null?`
ObsiCLI was closed correctly.`:t;this.out(n),o(this,e).setAttribute("disabled","disabled"),o(this,e).value="",l(this,u,a).call(this,"closed")}clear(){o(this,s).innerHTML="",o(this,e).value="",o(this,e).focus()}}s=new WeakMap,e=new WeakMap,r=new WeakMap,u=new WeakSet,v=function(){const t=this.querySelector(".input");t instanceof HTMLFormElement&&t.addEventListener("submit",l(this,u,b).bind(this)),this.addEventListener("click",l(this,u,m).bind(this)),o(this,e).addEventListener("input",n=>n.stopPropagation())},a=function(t,n={}){const c=new CustomEvent(t,{detail:n});this.dispatchEvent(c)},b=function(t){t.preventDefault(),this.out(o(this,e).value),o(this,r).resolve(o(this,e).value),l(this,u,a).call(this,"input",o(this,e).value),t.currentTarget.reset(),h(this,r,{resolve:()=>{},reject:()=>{}})},m=function(){requestAnimationFrame(()=>{const t=window.getSelection();let n=!1;t.isCollapsed||t.anchorNode.parentNode.closest("obsi-cli")===this&&(n=!0),n||o(this,e).focus()})},customElements.define("obsi-cli",i)}));
